In [ ]:
from sklearn import datasets

In [ ]:
iris = datasets.load_iris()

## 데이터 파악하기

> 이 데이터는 어떻게 생겨먹었냐?

```py
print(iris)
```

In [ ]:
# print(iris)
# print(iris['data'])
print(iris['data'])
print(iris['data'].shape) # (150, 4)
print(iris['target'].shape) # (150, )
print(iris['target_names'])
print(iris['target_names'][iris['target'][0]])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
from sklearn.model_selection import train_test_split

X = iris['data']
y = iris['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=4)

In [ ]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


## k-Nearest Neighbor (kNN) 알고리즘

* 분류 알고리즘
* 일반적으로 $k = 5$ , $k = 3$ 로 잡음
* 주변의 가까운 $k$ 개를 가져와서 $k$개의 클래스를 파악

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=6) # k = 6
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [ ]:
y_pred = knn.predict(X_test)
print(y_pred)

from sklearn import metrics
scores = metrics.accuracy_score(y_test, y_pred)
print(scores)

[2 0 2 2 2 1 2 0 0 2 0 0 0 1 2 0 1 0 0 2 0 2 1 0 0 0 0 0 0 2]
0.9666666666666667


### 결과 분석

**혼동행렬**

| pred \\ true | 0 | 1 | 2 |
| :-: | :-: | :-: | :-: |
| 0 | 16 | ? | ? |
| 1 | ? | 4 | 1 |
| 2 | ? | ? | 9 |


**한 클래스에 대한 민감도, 특이도**

$Accuracy = \frac{True Sample}{Total Sample} = frac{29}{30} = 96.6\%$

<br>

**$0$ 번 클래스에 대한 민감도, 특이도**

| pred \\ true | P = 0 | N = 1, 2 |
| :-: | :-: | :-: |
| p = 0 | 16 | 0 |
| N = 1, 2 | 0 | 14 |

<br>

**$1$ 번 클래스에 대한 민감도, 특이도**

| pred \\ true | P = 1 | N = 0, 2 |
| :-: | :-: | :-: |
| p = 1 | 4 | 1 |
| N = 0, 2 | 0 | 25 |

<br>

**$2$ 번 클래스에 대한 민감도, 특이도**

| pred \\ true | P = 2 | N = 0, 1 |
| :-: | :-: | :-: |
| p = 2 | 9 | 0 |
| N = 0, 1 | 1 | 20 |


In [ ]:
matrix = metrics.confusion_matrix(y_test, y_pred)
print(matrix)

[[16  0  0]
 [ 0  4  1]
 [ 0  0  9]]


## 과제 의도

X_train

| 0 | 1 | 2 | 3 |
| :-: | :-: | :-: | :-: |

y_train

| 0 |
| :-: |

```py
for x in x_test:
  x - x_train
```

In [ ]:
import numpy as np

a = np.array([
    [91, 92, 93],
    [2, 3, 4]
])
b = np.array([3, 3, 3])
print(a - b)
print(a)
print(len(a), a.size, a.shape, len(a.shape))
print(np.c_[a, [i for i in range(a.shape[0])]])
hs = np.c_[a, [i for i in range(a.shape[0])]]
print(hs)
print(np.sort(hs, 0))
print(a)
x = [*map(lambda each: list(each), hs)]
sorted(x)

[[88 89 90]
 [-1  0  1]]
[[91 92 93]
 [ 2  3  4]]
2 6 (2, 3) 2
[[91 92 93  0]
 [ 2  3  4  1]]
[[91 92 93  0]
 [ 2  3  4  1]]
[[ 2  3  4  0]
 [91 92 93  1]]
[[91 92 93]
 [ 2  3  4]]


[[2, 3, 4, 1], [91, 92, 93, 0]]

In [ ]:
numpy